export { mergeConfig, readConfigFile, writeConfigFile } from './config-writer.js';
export type { ServerConfigEntry } from './config-writer.js';
export { CLAUDE_CODE_CLIENT_ID, claudeCodeConfigPath } from './claude-code-adapter.js';
export { CURSOR_CLIENT_ID, cursorConfigPath } from './cursor-adapter.js';
export { VSCODE_CLIENT_ID, vscodeConfigPath } from './vscode-adapter.js';
export { activateForClient, deactivateForClient, configPathFor, configKeyFor } from './activate.js';
export { runWrapper } from './run-wrapper.js';
export type { RunWrapperDeps, SpawnFn } from './run-wrapper.js';
export { detectDriftForPair, detectAllDrift } from './drift.js';
export type { DriftStatus, DriftEntry, DriftCheckResult } from './drift.js';
export { resolveDriftEntry, validResolutionsFor } from './drift-resolve.js';
export type { DriftResolution, ResolveResult } from './drift-resolve.js';
export { DriftError, malformedConfigStructureError } from './drift-errors.js';
export type { DriftErrorCategory } from './drift-errors.js';
